version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=garcia
      - POSTGRES_PASSWORD=my_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  spring-boot-server:
    build:
      context: ./hotelmanagerBE
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_BOOT_SERVER_URL: http://spring-boot-server:8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotelmanager
      SPRING_DATASOURCE_USERNAME: garcia
      SPRING_DATASOURCE_PASSWORD: my_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  nuxtjs-client:
    environment:
      - SPRING_BOOT_SERVER_URL=http://spring-boot-server:8080
    build:
      context: ./hotelmanagerFE
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-server
