version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: garcia
      POSTGRES_PASSWORD: localhost
      POSTGRES_DB: hotelmanager
    ports:
      - "127.0.0.1::5432"

  spring-boot-server:
    build:
      context: ./hotelmanagerBE
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotelmanager
      SPRING_DATASOURCE_USERNAME: garcia
      SPRING_DATASOURCE_PASSWORD: localhost
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - .m2:/root/.m2
  nuxtjs-client:
    build:
      context: ./hotelmanagerFE
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-server
